# Generated by Django 5.0.7 on 2024-07-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tendencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='publicacion')),
                ('datos', models.TextField()),
                ('director', models.TextField()),
                ('director2', models.TextField()),
                ('escritor', models.TextField()),
            ],
        ),
    ]
