# Generated by Django 5.0.7 on 2024-07-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendencias', '0002_pelicula_delete_tendencias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='datos',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='director2',
            new_name='genero',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='escritor',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
    ]
